### ISSUE TITLE
this work but

### ISSUE THREAD

**Issue by mryigit** [kronoscloud/Instagram-Account-Creation-Tool#1]
this code work but account created by this program i cant login manuel instagram want phone number

**Comment by kronoscloud** [comment]
Hey, I can't currently check this issue for you at the moment as all of my IPs have been banned from instagrams api. Although I believe providing a false number should be fine.

**Comment by mryigit** [comment]
No man i tried after set number instagram ask me sms code

**Comment by kronoscloud** [comment]
Hmm I'm not to sure I will look in to it, I have others who are using it and not running in to this issue.
