### ISSUE TITLE
release build link?

### ISSUE THREAD

**Issue by sejkii** [kronoscloud/Instagram-Account-Creation-Tool#3]
Or download the release build from the releases page.

Where can i find the release build?

thanks for the work!

**Comment by kronoscloud** [comment]
https://github.com/kronoscloud/Instagram-Account-Creation-Tool/releases

**Comment by sejkii** [comment]
Awesome man! Thank you.

Btw you maybe add festures? Like uploading pics and profile pic after creating the acc

**Comment by sejkii** [comment]
Oh ok. Is there anyway I can contact you. (Email?)

**Comment by kronoscloud** [comment]
Discord: Sloth#4064

**Comment by sejkii** [comment]
Hey added you. And sent friend request.

Regards

**Comment by kronoscloud** [comment]
What's you discord username don't seem to have you in my requests list.
